# Generated by Django 5.1.4 on 2025-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
